---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}.{{ domain_name }}"
  when: set_hostname | bool

- name: Ensure system is up to date
  yum:
    name: "*"
    state: latest
  when: update_system | bool
  notify: reboot

- name: Ensure important and useful packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - chrony
      - libselinux-python
      - man
      - tmux
      - vim-enhanced
      - wget

- name: Ensure SELinux is disabled
  selinux:
    state: disabled
  when: disable_selinux | bool
  notify: reboot

- name: Ensure that IPv6 is disabled
  lineinfile:
    dest: /etc/default/grub
    line: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX ipv6.disable=1"
    state: present
  when: disable_ipv6 | bool
  notify: reboot

- name: Ensure that common sysctl tunables are set
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes
  loop:
    - { name: 'vm.swappiness', value: 1 }
  when: enable_sysctl_tunables | bool

- name: Ensure that Transparent Hugepages are disabled
  lineinfile:
    dest: /etc/default/grub
    line: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX transparent_hugepage=never"
    state: present
  when: disable_thp | bool
  notify:
    - update grub
    - reboot

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ^%wheel
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  when: enable_passwordless_sudo | bool

- name: Ensure Chrony uses correct NTP servers
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  when: update_chrony_ntp_servers | bool
  notify: restart chronyd

- name: Update facts to reflect new hostname
  setup:

- name: Ensure /etc/hosts is in place
  template:
    src: hosts.j2
    dest: '/etc/hosts'
    owner: root
    group: root
    mode: 0644
  when: update_hosts | bool
